### ISSUE TITLE
Bug found in Edit Command

### ISSUE THREAD

**Issue by Benjykoh** [AY2122S2-CS2103T-W09-4/tp#139]
I found 2 bugs within the Edit Command,

- When I try to edit the Module Code for a Student, it edits their Name instead.
- Whenever a field is updated, the tasklist seems to reset.

<img width="377" alt="image" src="https://user-images.githubusercontent.com/65704109/160876078-511811a0-2493-4a43-9a73-edd9e70704ff.png">

<img width="379" alt="image" src="https://user-images.githubusercontent.com/65704109/160876367-dcb8b744-4cf1-43fb-8a9b-afeffc46bd07.png">

Steps to recreate this bug:
1. Add a new student
2. Assign a task to the student
3. Edit any field

Current Outcome:
1. All tasks will be removed
2. If the module code is supposed to be edited, the name will be edited instead.

**Comment by Korochii** [comment]
Managed to replicate the tasklist problem as well. Will look into it later.

**Comment by Korochii** [comment]
For now, I agree that the tasklist is not copied over, since we did not include in the createEditedPerson method. Should be an easy fix if everything goes well

**Comment by Korochii** [comment]
Linked to #134 as the PR solves both bugs
