### ISSUE TITLE
[PE-D] Commands don't work properly when waiting for clear confirmation

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103T-W09-4/tp#145]
![image.png](https://raw.githubusercontent.com/snss231/ped/main/files/799917cb-410b-45cb-a458-3d530958ea27.png)

![image.png](https://raw.githubusercontent.com/snss231/ped/main/files/c6e4d85e-b9b9-4d25-9dcf-c7d8baffb4c4.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: snss231/ped#1

**Comment by Korochii** [comment]
Can be fixed by adding extra info to UG
