### ISSUE TITLE
[PE-D] Doesn't make sense to be able to add contacts with same telegram handle

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103T-W09-4/tp#157]
![image.png](https://raw.githubusercontent.com/snss231/ped/main/files/82b9fc8e-1ca2-4738-8abb-7eadc78c89f3.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: snss231/ped#8

**Comment by brelkh** [comment]
Need to update DG to warn users about duplicate detection limitations.

![image](https://user-images.githubusercontent.com/46317008/161386703-379f44bd-b1b5-451e-ab42-64f1db0a7c08.png)

**Comment by brelkh** [comment]
@Harish-coding This note already exists in the UG under `add` command, "all other fields do not have to be unique".

<img width="629" alt="image" src="https://user-images.githubusercontent.com/46317008/162629884-4ee1613e-3723-4319-b10b-f13cf426976d.png">

If you think this suffices as an explanation for this PE-D bug, then I think this issue can be closed 👍

**Comment by Korochii** [comment]
![image](https://user-images.githubusercontent.com/65613207/162630063-836cb898-cc6a-46d6-9797-bab976908e70.png)
I have reiterated it here as well :smiley:
