### ISSUE TITLE
[PE-D] Edit fields are not all optional

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103T-W09-4/tp#159]
User is not allowed to simply input edit command without all fields being absent, which contradicts the UG that all fields are optional.

### To replicate:
Type `edit 1` to get error message "At least one field to edit must be provided."

### Intended result:
Should return edit command with successful edit result (though nothing was edited) with fields being the same as before.

![image.png](https://raw.githubusercontent.com/juslam19/ped/main/files/c2616ee0-6ffd-48a7-8954-276453c40d14.png)

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: juslam19/ped#2

**Comment by Korochii** [comment]
Update UG (and maybe DG)
