### ISSUE TITLE
Fix UX bug related to clear command

### ISSUE THREAD

**Issue by brelkh** [AY2122S2-CS2103T-W09-4/tp#73]
As mentioned in the "Bugs/Potential Improvements" in #61, improvements can be made to code quality, and the UX when using the clear command. Currently, when a user inputs `clear`, they have to click the CommandBox again before they are able to input `confirm`. 

Ideally, they should be able to input `confirm` without needing to click the CommandBox (similar to all other commands).

**Comment by Korochii** [comment]
Closing since I'm not sure how to fix this before v1.3 ends
